services:
  docs:
    image: spotter_api_local_docs
    container_name: spotter_api_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./spotter_api:/app/spotter_api:z
    ports:
      - '9000:9000'
    command: /start-docs
